[package]
name = "flight-sensor"
version = "0.1.0"
edition = "2021"

[dependencies]
vl53l4cd = "0.4.0"
linux-embedded-hal-async = {path = './linux-embedded-hal-async'}
i2cdev = "0.6.1"
tokio = {version="1.12.0", features = ["full"]}

